//! `lvz-agent` — the reasoning loop (`RECIPE.md` §4, §6.3).
//!
//! The agent runs a **plan → act → observe** cycle: ask the provider for a turn, and if the
//! model called tools, execute them, append the results to history, and ask again — until
//! the model answers without calling a tool (or a safety/budget limit trips). It consumes
//! only the [`Provider`] and [`Tool`] contracts plus a [`ToolRegistry`], so it is unaware of
//! any wire protocol or gateway.
//!
//! Efficiency hardening (§6.3) lives here:
//! - **Caching** is capability-gated (§6.2): the stable prefix (system prompt + tool
//!   definitions) is marked cacheable only when the provider advertises
//!   [`prompt_caching`](lvz_protocol::Capabilities::prompt_caching).
//! - **History compaction** summarises old turns once the transcript exceeds the
//!   [`compact_after`](Knobs::compact_after) knob, keeping the original task and the most
//!   recent turns verbatim. The summary is generated by a separate, tool-less provider call
//!   that can be **routed to a cheaper model** ([`AgentConfig::summary_model`]) — model
//!   tiering for the routing/summary workload.
//! - **Tool-result truncation** caps oversized outputs head/tail.
//! - The efficiency dials are [`Knobs`] chosen by a [`Tuner`] (default [`NoopTuner`] = the
//!   static §6.5 baseline), and the realised [`Outcome`] is reported back so an ATO learner
//!   (`lvz-tune`, §6.6) can be swapped in without touching the agent.
//!
//! Token usage is summed across every round-trip — including the compaction call — which is
//! the metric that matters (§6.4) and is enforced against an optional budget.

use std::collections::HashMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use async_trait::async_trait;
use futures::channel::mpsc;
use futures::stream::{BoxStream, StreamExt};
use lvz_context::tokens::estimate_tokens;
use lvz_protocol::{
    AgentError, AgentHandle, Archetype, Capabilities, ChatRequest, ContentBlock, Event, Knobs,
    Message, ModelTier, NoopTuner, Outcome, Provider, RepoProfile, Role, StopReason, SystemPrompt,
    TaskContext, ToolDef, Tuner, TurnRequest, Usage,
};
use lvz_tools::ToolRegistry;
use serde_json::{json, Value};

const DEFAULT_SYSTEM: &str = "You are Lavoisier, a terse, token-efficient coding agent. \
Use the provided tools to inspect and modify the repository. To save tokens, prefer \
outline_file over read_file to learn a file's structure, and prefer read_anchored + \
edit_anchored over rewriting whole files with write_file. Take minimal, targeted actions; \
do not narrate. When the task is complete, give a one-line summary.";

/// System prompt for the compaction summariser (§6.3). Terse, structured, fact-preserving.
const COMPACTION_SYSTEM: &str = "You compress a coding agent's transcript so it can keep \
working with fewer tokens. Produce a terse note that preserves: files inspected or edited \
(with their paths), key findings, decisions made, and any steps still pending. Use short \
bullet lines. Omit pleasantries and reasoning narration. Output only the note.";

/// Generation ceiling for a compaction summary — summaries are meant to be short.
const SUMMARY_MAX_TOKENS: u32 = 512;

/// Number of trailing (assistant, tool-result) turn-pairs kept verbatim when compacting.
const KEEP_RECENT_TURNS: usize = 2;

/// Tunable settings for an agent run that are *not* efficiency knobs (those are [`Knobs`],
/// chosen per task by a [`Tuner`]).
#[derive(Clone, Debug)]
pub struct AgentConfig {
    /// Model id passed to the provider each turn.
    pub model: String,
    /// Per-turn generation ceiling.
    pub max_tokens: u32,
    /// System prompt (the stable prefix; cached when the provider supports it).
    pub system: String,
    /// Safety cap on tool round-trips before forcing a stop.
    pub max_steps: usize,
    /// Optional ceiling on total task tokens across all round-trips (§6.4).
    pub token_budget: Option<u64>,
    /// Coarse tier of [`model`](Self::model); conditions tuner knob selection (§6.6).
    pub model_tier: ModelTier,
    /// Cheaper model id used for history-compaction summaries (§6.3 model routing). When
    /// `None`, summaries reuse [`model`](Self::model).
    pub summary_model: Option<String>,
    /// Soft per-request ceiling on estimated context tokens (§6.3 context-budget manager).
    /// When set and exceeded even after compaction, the oldest tool-result content is evicted.
    /// Distinct from [`token_budget`](Self::token_budget), which caps the *whole task*.
    pub context_limit: Option<usize>,
    /// Repository root to profile for the tuner's [`TaskContext`] (§6.6). `None` skips the
    /// filesystem walk and uses an empty [`RepoProfile`] — fine for the [`NoopTuner`] default.
    pub repo_root: Option<PathBuf>,
}

impl Default for AgentConfig {
    fn default() -> Self {
        Self {
            model: "grok-4".to_string(),
            max_tokens: 4096,
            system: DEFAULT_SYSTEM.to_string(),
            max_steps: 12,
            token_budget: None,
            model_tier: ModelTier::Balanced,
            summary_model: None,
            context_limit: None,
            repo_root: None,
        }
    }
}

impl AgentConfig {
    /// Set the model id (builder style).
    pub fn with_model(mut self, model: impl Into<String>) -> Self {
        self.model = model.into();
        self
    }

    /// Set the total-task token budget.
    pub fn with_budget(mut self, budget: u64) -> Self {
        self.token_budget = Some(budget);
        self
    }

    /// Route history-compaction summaries to a cheaper model (§6.3 model tiering).
    pub fn with_summary_model(mut self, model: impl Into<String>) -> Self {
        self.summary_model = Some(model.into());
        self
    }

    /// Set the soft per-request context-token ceiling (§6.3 context-budget manager).
    pub fn with_context_limit(mut self, limit: usize) -> Self {
        self.context_limit = Some(limit);
        self
    }

    /// Profile this repository root to give the tuner a real [`RepoProfile`] (§6.6).
    pub fn with_repo_root(mut self, root: impl Into<PathBuf>) -> Self {
        self.repo_root = Some(root.into());
        self
    }
}

/// A [`Tuner`] that always returns a fixed [`Knobs`] and ignores observations — for callers
/// that want explicit, non-adaptive knob settings (a `--compact-after`-style override, tests)
/// without pulling in the `lvz-tune` learner.
#[derive(Debug, Clone, Copy)]
pub struct FixedTuner(pub Knobs);

impl Tuner for FixedTuner {
    fn select(&self, _ctx: &TaskContext) -> Knobs {
        self.0
    }
    fn observe(&self, _ctx: &TaskContext, _used: &Knobs, _out: &Outcome) {}
}

/// The reasoning loop bound to a concrete provider, tool set, and tuner.
pub struct Agent {
    provider: Arc<dyn Provider>,
    tools: ToolRegistry,
    config: AgentConfig,
    tuner: Arc<dyn Tuner>,
}

impl Agent {
    pub fn new(provider: Arc<dyn Provider>, tools: ToolRegistry, config: AgentConfig) -> Self {
        Self {
            provider,
            tools,
            config,
            tuner: Arc::new(NoopTuner),
        }
    }

    /// Use a specific tuner (e.g. [`FixedTuner`], or an `lvz-tune` learner) instead of the
    /// default [`NoopTuner`].
    pub fn with_tuner(mut self, tuner: Arc<dyn Tuner>) -> Self {
        self.tuner = tuner;
        self
    }

    /// Run one task to completion, streaming normalised events as they are produced.
    ///
    /// Per-round-trip `Usage`/`Done` events are suppressed; the caller sees exactly one
    /// terminal `Usage` (the task total, including any compaction call) followed by one `Done`.
    pub fn run(&self, input: impl Into<String>) -> BoxStream<'static, Result<Event, AgentError>> {
        let (tx, rx) = mpsc::unbounded();
        let provider = self.provider.clone();
        let tools = self.tools.clone();
        let config = self.config.clone();
        let tuner = self.tuner.clone();
        let input = input.into();

        tokio::spawn(async move {
            run_loop(provider, tools, config, tuner, input, &tx).await;
            // tx drops here, closing the stream.
        });

        rx.boxed()
    }
}

#[async_trait]
impl AgentHandle for Agent {
    async fn submit(
        &self,
        turn: TurnRequest,
    ) -> Result<BoxStream<'static, Result<Event, AgentError>>, AgentError> {
        Ok(self.run(turn.input))
    }
}

type Sink = mpsc::UnboundedSender<Result<Event, AgentError>>;

async fn run_loop(
    provider: Arc<dyn Provider>,
    tools: ToolRegistry,
    config: AgentConfig,
    tuner: Arc<dyn Tuner>,
    input: String,
    tx: &Sink,
) {
    let tool_defs = tools.defs();
    let caps = provider.capabilities();
    let ctx = TaskContext {
        archetype: classify_archetype(&input),
        repo: config
            .repo_root
            .as_deref()
            .map(profile_repo)
            .unwrap_or_default(),
        caps,
        model: config.model_tier,
    };
    let knobs = tuner.select(&ctx);

    let mut history: Vec<Message> = vec![Message::user(input)];
    let mut total = Usage::default();
    let mut round_trips: u32 = 0;

    for _step in 0..config.max_steps {
        // History compaction (§6.3): once the transcript outgrows the knob, summarise the
        // middle turns (routed to the cheaper summary model) before the next request. The
        // summary call's tokens count toward the task total (§6.4).
        if history_tokens(&history) > knobs.compact_after {
            if let Some(compacted) = compact_history(&provider, &config, &history).await {
                total.accumulate(&compacted.usage);
                history = compacted.history;
            }
        }

        // Context-budget manager (§6.3): if the request would still blow the per-request
        // ceiling (e.g. a single huge recent tool result that compaction can't touch), evict
        // the oldest tool-result content until it fits.
        if let Some(limit) = config.context_limit {
            evict_to_fit(&mut history, limit);
        }

        let req = build_request(&config, &tool_defs, &caps, &history);
        let mut stream = match provider.stream(req).await {
            Ok(s) => s,
            Err(e) => {
                observe(&tuner, &ctx, &knobs, &total, round_trips, false);
                let _ = tx.unbounded_send(Err(AgentError::Provider(e.to_string())));
                return;
            }
        };

        let mut turn = TurnAccumulator::default();
        while let Some(event) = stream.next().await {
            match event {
                Ok(event) => {
                    if let Some(forward) = turn.observe(event) {
                        let _ = tx.unbounded_send(Ok(forward));
                    }
                }
                Err(e) => {
                    observe(&tuner, &ctx, &knobs, &total, round_trips, false);
                    let _ = tx.unbounded_send(Err(AgentError::Provider(e.to_string())));
                    return;
                }
            }
        }

        round_trips += 1;
        total.accumulate(&turn.usage);

        if let Some(budget) = config.token_budget {
            if total.total() > budget {
                observe(&tuner, &ctx, &knobs, &total, round_trips, false);
                let _ = tx.unbounded_send(Err(AgentError::BudgetExceeded));
                return;
            }
        }

        if turn.tool_calls.is_empty() {
            let stop = turn.stop.unwrap_or(StopReason::EndTurn);
            observe(&tuner, &ctx, &knobs, &total, round_trips, true);
            let _ = tx.unbounded_send(Ok(Event::Usage(total)));
            let _ = tx.unbounded_send(Ok(Event::Done(stop)));
            return;
        }

        // Echo the assistant's text + tool calls into history, then run the tools.
        history.push(turn.to_assistant_message());

        let mut results = Vec::with_capacity(turn.tool_calls.len());
        for call in &turn.tool_calls {
            let block = match tools.invoke(&call.name, call.parsed_args()).await {
                Ok(out) => ContentBlock::ToolResult {
                    tool_use_id: call.id.clone(),
                    content: truncate(&out.content, knobs.truncate_bytes),
                    is_error: out.is_error,
                },
                Err(e) => ContentBlock::ToolResult {
                    tool_use_id: call.id.clone(),
                    content: format!("tool error: {e}"),
                    is_error: true,
                },
            };
            results.push(block);
        }
        history.push(Message {
            role: Role::User,
            content: results,
        });
    }

    // Ran out of steps without a final answer.
    observe(&tuner, &ctx, &knobs, &total, round_trips, false);
    let _ = tx.unbounded_send(Ok(Event::Usage(total)));
    let _ = tx.unbounded_send(Ok(Event::Done(StopReason::Other("max_steps".into()))));
}

/// Report the realised task outcome to the tuner so it can adapt knobs (`RECIPE.md` §6.6).
fn observe(
    tuner: &Arc<dyn Tuner>,
    ctx: &TaskContext,
    knobs: &Knobs,
    total: &Usage,
    round_trips: u32,
    success: bool,
) {
    tuner.observe(
        ctx,
        knobs,
        &Outcome {
            total_tokens: total.total(),
            round_trips,
            cache_hit_rate: total.cache_hit_rate(),
            success,
        },
    );
}

/// The result of a successful compaction: a shrunken history and the tokens it cost.
struct Compacted {
    history: Vec<Message>,
    usage: Usage,
}

/// Summarise the middle of `history` into one note via a tool-less provider call (routed to
/// [`AgentConfig::summary_model`] when set). Returns `None` — leaving history untouched — if
/// there is too little to compact or the summary call yields nothing.
///
/// The original task (`history[0]`) and the last [`KEEP_RECENT_TURNS`] turn-pairs are kept
/// verbatim; the slice between them is replaced by a single user note. The cut lands on a
/// turn boundary so assistant `tool_use` blocks are never separated from their `tool_result`.
async fn compact_history(
    provider: &Arc<dyn Provider>,
    config: &AgentConfig,
    history: &[Message],
) -> Option<Compacted> {
    let keep = 2 * KEEP_RECENT_TURNS;
    // Need the task message + at least one full (assistant, result) pair to summarise + the
    // recent tail. History is always `[user] then (assistant, user)*`, so this index lands on
    // an assistant message and the summarised prefix ends on a complete tool-result message.
    if history.len() < keep + 3 {
        return None;
    }
    let cut_end = history.len() - keep;

    let transcript = render_transcript(&history[1..cut_end]);
    let summary_model = config
        .summary_model
        .clone()
        .unwrap_or_else(|| config.model.clone());
    let req = ChatRequest::new(summary_model)
        .max_tokens(SUMMARY_MAX_TOKENS)
        .system(COMPACTION_SYSTEM)
        .push(Message::user(transcript));

    let mut stream = provider.stream(req).await.ok()?;
    let mut summary = String::new();
    let mut usage = Usage::default();
    while let Some(event) = stream.next().await {
        match event {
            Ok(Event::TextDelta(t)) => summary.push_str(&t),
            Ok(Event::Usage(u)) => usage = u,
            Ok(_) => {}
            Err(_) => return None,
        }
    }
    if summary.trim().is_empty() {
        return None;
    }

    let mut new_history = Vec::with_capacity(2 + keep);
    new_history.push(history[0].clone());
    new_history.push(Message::user(format!(
        "[Earlier conversation compacted to save tokens]\n{summary}"
    )));
    new_history.extend_from_slice(&history[cut_end..]);
    Some(Compacted {
        history: new_history,
        usage,
    })
}

/// Render messages to a plain-text transcript for the summariser (tool blocks flattened to
/// text, since the summary request advertises no tools).
fn render_transcript(messages: &[Message]) -> String {
    let mut out = String::new();
    for m in messages {
        let role = match m.role {
            Role::User => "user",
            Role::Assistant => "assistant",
        };
        for block in &m.content {
            match block {
                ContentBlock::Text { text, .. } | ContentBlock::Thinking { text } => {
                    let _ = writeln!(out, "{role}: {text}");
                }
                ContentBlock::ToolUse { name, input, .. } => {
                    let _ = writeln!(out, "{role} called {name}({input})");
                }
                ContentBlock::ToolResult {
                    content, is_error, ..
                } => {
                    let tag = if *is_error { " (error)" } else { "" };
                    let _ = writeln!(out, "tool result{tag}: {content}");
                }
            }
        }
    }
    out
}

/// Estimate the token footprint of the whole transcript, including tool-call args and tool
/// results (which dominate size) — the trigger for compaction.
fn history_tokens(history: &[Message]) -> usize {
    history.iter().map(|m| estimate_tokens(&proxy(m))).sum()
}

/// Relevance-ranked context eviction (`RECIPE.md` §6.3). When the assembled history still
/// exceeds the per-request `limit` — typically because a single recent tool result is huge and
/// compaction can't summarise the protected recent window — replace the *content* of the
/// oldest tool-result blocks (oldest = least relevant) with a short placeholder, working
/// forward until the estimate is under `limit` or nothing more is evictable. The task message,
/// the last [`KEEP_RECENT_TURNS`] turns, and all message structure (so `tool_use`/`tool_result`
/// pairing stays intact) are preserved.
fn evict_to_fit(history: &mut [Message], limit: usize) {
    if history_tokens(history) <= limit {
        return;
    }
    let protected = 2 * KEEP_RECENT_TURNS;
    let evictable_end = history.len().saturating_sub(protected);
    for i in 1..evictable_end {
        let mut changed = false;
        for block in &mut history[i].content {
            if let ContentBlock::ToolResult { content, .. } = block {
                if !content.starts_with("[evicted") {
                    let n = content.len();
                    *content = format!("[evicted: {n} bytes of older tool output]");
                    changed = true;
                }
            }
        }
        // Re-estimate only after a change; the mutable borrow above has ended.
        if changed && history_tokens(history) <= limit {
            return;
        }
    }
}

/// A token-estimation proxy for a message: all text plus tool names/args/results.
fn proxy(m: &Message) -> String {
    let mut s = String::new();
    for block in &m.content {
        match block {
            ContentBlock::Text { text, .. } | ContentBlock::Thinking { text } => s.push_str(text),
            ContentBlock::ToolUse { name, input, .. } => {
                s.push_str(name);
                s.push_str(&input.to_string());
            }
            ContentBlock::ToolResult { content, .. } => s.push_str(content),
        }
        s.push(' ');
    }
    s
}

/// Cheap keyword classifier mapping a task prompt to an [`Archetype`] prior (`RECIPE.md`
/// §6.5/§6.6). Deterministic and free — a good-enough prior for keying tuner profiles, with
/// no extra round-trip. Ordering is intentional: more specific intents win (a rename is a
/// refactor, an "add" is more specific than a generic edit). A future version could route
/// genuinely ambiguous prompts to a cheap classification model (§6.3).
fn classify_archetype(prompt: &str) -> Archetype {
    let p = prompt.to_lowercase();
    let has = |kw: &str| p.contains(kw);
    if has("rename") {
        Archetype::Rename
    } else if has("refactor")
        || has("extract ")
        || has("restructure")
        || has("split ")
        || has("move ")
    {
        Archetype::Refactor
    } else if has("implement")
        || has("add ")
        || has("create ")
        || has("new feature")
        || has("support for")
        || has("build ")
    {
        Archetype::Feature
    } else if has("fix")
        || has("edit")
        || has("change")
        || has("update")
        || has("modify")
        || has("rewrite")
    {
        Archetype::SingleFileEdit
    } else {
        Archetype::Other
    }
}

/// Build a [`RepoProfile`] by a bounded walk of `root`, skipping VCS/build/dependency dirs.
/// Counts files, sums their bytes, and picks the most common recognised source language
/// (`RECIPE.md` §6.6 — repo shape conditions knob selection). Best-effort: unreadable entries
/// are skipped and the walk is capped so a huge monorepo can't stall task start.
fn profile_repo(root: &Path) -> RepoProfile {
    const MAX_FILES: u32 = 20_000;
    fn skip_dir(name: &str) -> bool {
        name.starts_with('.')
            || matches!(
                name,
                "target" | "node_modules" | "dist" | "build" | "vendor" | "__pycache__"
            )
    }
    fn lang_of(path: &Path) -> Option<&'static str> {
        use lvz_context::Lang::*;
        match lvz_context::Lang::from_path(path.to_str()?) {
            Some(Rust) => Some("rust"),
            Some(Python) => Some("python"),
            Some(JavaScript) => Some("javascript"),
            Some(TypeScript) => Some("typescript"),
            None => None,
        }
    }

    let mut file_count = 0u32;
    let mut total_bytes = 0u64;
    let mut lang_counts: HashMap<&'static str, u32> = HashMap::new();
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        if file_count >= MAX_FILES {
            break;
        }
        let entries = match std::fs::read_dir(&dir) {
            Ok(e) => e,
            Err(_) => continue,
        };
        for entry in entries.flatten() {
            let Ok(ft) = entry.file_type() else { continue };
            let path = entry.path();
            if ft.is_dir() {
                let name = entry.file_name();
                if !skip_dir(&name.to_string_lossy()) {
                    stack.push(path);
                }
            } else if ft.is_file() {
                file_count += 1;
                if let Ok(meta) = entry.metadata() {
                    total_bytes += meta.len();
                }
                if let Some(lang) = lang_of(&path) {
                    *lang_counts.entry(lang).or_default() += 1;
                }
                if file_count >= MAX_FILES {
                    break;
                }
            }
        }
    }
    let primary_language = lang_counts
        .into_iter()
        .max_by_key(|(_, c)| *c)
        .map(|(l, _)| l.to_string())
        .unwrap_or_default();
    RepoProfile {
        file_count,
        total_bytes,
        primary_language,
    }
}

/// Assemble a request, marking the stable prefix cacheable iff the provider supports caching.
fn build_request(
    config: &AgentConfig,
    tool_defs: &[ToolDef],
    caps: &Capabilities,
    history: &[Message],
) -> ChatRequest {
    let mut req = ChatRequest::new(config.model.clone()).max_tokens(config.max_tokens);
    req.system = Some(SystemPrompt {
        text: config.system.clone(),
        cache: caps.prompt_caching,
    });
    let mut defs = tool_defs.to_vec();
    if caps.prompt_caching {
        if let Some(last) = defs.last_mut() {
            last.cache = true; // breakpoint at the end of the stable tool-def prefix
        }
    }
    req.tools = defs;
    req.messages = history.to_vec();
    req
}

/// One in-flight tool call being reassembled from streamed argument deltas.
struct ToolCall {
    id: String,
    name: String,
    args_json: String,
}

impl ToolCall {
    /// Parse accumulated argument JSON, defaulting to `{}` when empty or malformed.
    fn parsed_args(&self) -> Value {
        if self.args_json.trim().is_empty() {
            json!({})
        } else {
            serde_json::from_str(&self.args_json).unwrap_or_else(|_| json!({}))
        }
    }
}

/// Folds a provider's event stream into a structured turn while deciding which events to
/// forward to the caller. Text/thinking/tool events pass through; usage/done are captured.
#[derive(Default)]
struct TurnAccumulator {
    text: String,
    tool_calls: Vec<ToolCall>,
    by_id: HashMap<String, usize>,
    usage: Usage,
    stop: Option<StopReason>,
}

impl TurnAccumulator {
    fn observe(&mut self, event: Event) -> Option<Event> {
        match event {
            Event::TextDelta(ref t) => {
                self.text.push_str(t);
                Some(event)
            }
            Event::Thinking(_) => Some(event),
            Event::ToolUseStart { ref id, ref name } => {
                self.by_id.insert(id.clone(), self.tool_calls.len());
                self.tool_calls.push(ToolCall {
                    id: id.clone(),
                    name: name.clone(),
                    args_json: String::new(),
                });
                Some(event)
            }
            Event::ToolUseDelta { ref id, ref json } => {
                if let Some(&pos) = self.by_id.get(id) {
                    self.tool_calls[pos].args_json.push_str(json);
                }
                Some(event)
            }
            Event::ToolUseEnd { .. } => Some(event),
            Event::Usage(u) => {
                self.usage = u; // providers emit one usage per turn; last wins
                None
            }
            Event::Done(s) => {
                self.stop = Some(s);
                None
            }
        }
    }

    fn to_assistant_message(&self) -> Message {
        let mut content = Vec::new();
        if !self.text.is_empty() {
            content.push(ContentBlock::text(self.text.clone()));
        }
        for call in &self.tool_calls {
            content.push(ContentBlock::ToolUse {
                id: call.id.clone(),
                name: call.name.clone(),
                input: call.parsed_args(),
            });
        }
        Message {
            role: Role::Assistant,
            content,
        }
    }
}

/// Head/tail truncation for oversized tool output, preserving both ends with a byte count.
fn truncate(s: &str, max_bytes: usize) -> String {
    if s.len() <= max_bytes {
        return s.to_string();
    }
    let keep_head = max_bytes * 2 / 3;
    let keep_tail = max_bytes / 3;
    let head: String = s.chars().take(keep_head).collect();
    let chars: Vec<char> = s.chars().collect();
    let tail_start = chars.len().saturating_sub(keep_tail);
    let tail: String = chars[tail_start..].iter().collect();
    let omitted = s.len().saturating_sub(head.len() + tail.len());
    format!("{head}\n... [{omitted} bytes truncated] ...\n{tail}")
}

#[cfg(test)]
mod tests {
    use super::*;
    use async_trait::async_trait;
    use futures::stream;
    use lvz_protocol::{Tool, ToolError, ToolOutput};
    use std::sync::atomic::{AtomicUsize, Ordering};
    use std::sync::Mutex;

    /// A provider that replays a fixed script of event lists, one per successive call.
    struct ScriptedProvider {
        calls: AtomicUsize,
        scripts: Vec<Vec<Event>>,
    }

    impl ScriptedProvider {
        fn new(scripts: Vec<Vec<Event>>) -> Arc<Self> {
            Arc::new(Self {
                calls: AtomicUsize::new(0),
                scripts,
            })
        }
    }

    #[async_trait]
    impl Provider for ScriptedProvider {
        async fn stream(
            &self,
            _req: ChatRequest,
        ) -> Result<
            BoxStream<'static, Result<Event, lvz_protocol::ProviderError>>,
            lvz_protocol::ProviderError,
        > {
            let n = self.calls.fetch_add(1, Ordering::SeqCst);
            let events = self.scripts.get(n).cloned().unwrap_or_default();
            Ok(stream::iter(events.into_iter().map(Ok)).boxed())
        }

        fn capabilities(&self) -> Capabilities {
            Capabilities::default()
        }
    }

    async fn collect(mut s: BoxStream<'static, Result<Event, AgentError>>) -> Vec<Event> {
        let mut out = Vec::new();
        while let Some(e) = s.next().await {
            out.push(e.expect("no agent error"));
        }
        out
    }

    #[tokio::test]
    async fn executes_a_tool_then_answers() {
        // Turn 1: call shell `echo lavoisier`. Turn 2: final text.
        let scripts = vec![
            vec![
                Event::ToolUseStart {
                    id: "t1".into(),
                    name: "shell".into(),
                },
                Event::ToolUseDelta {
                    id: "t1".into(),
                    json: "{\"command\":\"echo lavoisier\"}".into(),
                },
                Event::ToolUseEnd { id: "t1".into() },
                Event::Usage(Usage {
                    input_tokens: 50,
                    output_tokens: 10,
                    ..Default::default()
                }),
                Event::Done(StopReason::ToolUse),
            ],
            vec![
                Event::TextDelta("done".into()),
                Event::Usage(Usage {
                    input_tokens: 70,
                    output_tokens: 5,
                    ..Default::default()
                }),
                Event::Done(StopReason::EndTurn),
            ],
        ];
        let provider = ScriptedProvider::new(scripts);
        let agent = Agent::new(
            provider.clone(),
            ToolRegistry::with_builtins(),
            AgentConfig::default(),
        );

        let events = collect(agent.run("do it")).await;

        // The tool call streamed through.
        assert!(events
            .iter()
            .any(|e| matches!(e, Event::ToolUseStart { name, .. } if name == "shell")));
        // Final text present.
        assert!(events
            .iter()
            .any(|e| matches!(e, Event::TextDelta(t) if t == "done")));
        // Exactly one terminal Done, and it's the second turn's EndTurn.
        let dones: Vec<_> = events
            .iter()
            .filter(|e| matches!(e, Event::Done(_)))
            .collect();
        assert_eq!(dones.len(), 1);
        assert_eq!(dones[0], &Event::Done(StopReason::EndTurn));
        // Aggregate usage sums both round-trips: in 50+70=120, out 10+5=15.
        let usage = events
            .iter()
            .find_map(|e| match e {
                Event::Usage(u) => Some(*u),
                _ => None,
            })
            .expect("usage emitted");
        assert_eq!(usage.input_tokens, 120);
        assert_eq!(usage.output_tokens, 15);
        // Provider was called exactly twice.
        assert_eq!(provider.calls.load(Ordering::SeqCst), 2);
    }

    #[tokio::test]
    async fn enforces_token_budget() {
        let scripts = vec![vec![
            Event::TextDelta("hi".into()),
            Event::Usage(Usage {
                input_tokens: 1000,
                output_tokens: 1000,
                ..Default::default()
            }),
            Event::Done(StopReason::EndTurn),
        ]];
        let provider = ScriptedProvider::new(scripts);
        let agent = Agent::new(
            provider,
            ToolRegistry::new(),
            AgentConfig::default().with_budget(100),
        );

        let mut s = agent.run("hi");
        let mut saw_budget_error = false;
        while let Some(e) = s.next().await {
            if matches!(e, Err(AgentError::BudgetExceeded)) {
                saw_budget_error = true;
            }
        }
        assert!(saw_budget_error, "expected BudgetExceeded");
    }

    #[test]
    fn truncate_preserves_head_and_tail() {
        let s = "a".repeat(100);
        let out = truncate(&s, 30);
        assert!(out.starts_with('a'));
        assert!(out.contains("truncated"));
        assert!(out.len() < s.len() + 40);
    }

    #[test]
    fn evict_to_fit_drops_oldest_tool_results_and_keeps_recent() {
        // Realistic tool output: many whitespace-separated tokens (a single unbroken run
        // would estimate as ~1 token, unlike real file/shell output).
        let big = "lorem ipsum dolor sit amet ".repeat(160);
        let tu = |id: &str| Message {
            role: Role::Assistant,
            content: vec![ContentBlock::ToolUse {
                id: id.into(),
                name: "big".into(),
                input: json!({}),
            }],
        };
        let tr = |id: &str| Message {
            role: Role::User,
            content: vec![ContentBlock::ToolResult {
                tool_use_id: id.into(),
                content: big.clone(),
                is_error: false,
            }],
        };
        // task + 4 (assistant, result) pairs = 9 messages; KEEP_RECENT_TURNS=2 protects the
        // last 4, so the results at indices 2 and 4 are evictable; 6 and 8 are protected.
        let mut history = vec![
            Message::user("task"),
            tu("a"),
            tr("a"),
            tu("b"),
            tr("b"),
            tu("c"),
            tr("c"),
            tu("d"),
            tr("d"),
        ];
        let before = history_tokens(&history);
        evict_to_fit(&mut history, 10); // tiny limit forces eviction of all evictable results

        let content = |i: usize| match &history[i].content[0] {
            ContentBlock::ToolResult { content, .. } => content.clone(),
            _ => unreachable!("expected tool result at {i}"),
        };
        // Oldest two evicted...
        assert!(content(2).starts_with("[evicted"));
        assert!(content(4).starts_with("[evicted"));
        // ...recent two preserved verbatim, and the task untouched.
        assert_eq!(content(6), big);
        assert_eq!(content(8), big);
        assert_eq!(history[0].text(), "task");
        assert!(history_tokens(&history) < before);
    }

    #[test]
    fn classify_archetype_maps_intents() {
        use Archetype::*;
        assert_eq!(
            classify_archetype("Rename foo to bar across the crate"),
            Rename
        );
        assert_eq!(
            classify_archetype("Refactor the parser into modules"),
            Refactor
        );
        assert_eq!(
            classify_archetype("extract this block into a helper"),
            Refactor
        );
        assert_eq!(classify_archetype("Implement a retry policy"), Feature);
        assert_eq!(classify_archetype("add support for YAML config"), Feature);
        assert_eq!(
            classify_archetype("fix the off-by-one in range()"),
            SingleFileEdit
        );
        assert_eq!(classify_archetype("update the docstring"), SingleFileEdit);
        assert_eq!(classify_archetype("explain how the loop works"), Other);
        // Specificity ordering: a rename outranks the generic "change"/"refactor" it implies.
        assert_eq!(classify_archetype("change code: rename x to y"), Rename);
    }

    #[test]
    fn profile_repo_counts_source_and_skips_build_dirs() {
        let dir = std::env::temp_dir().join(format!("lvz_profile_{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(dir.join("src")).unwrap();
        std::fs::create_dir_all(dir.join("target/debug")).unwrap();
        std::fs::write(dir.join("src/a.rs"), "fn a() {}\n").unwrap();
        std::fs::write(dir.join("src/b.rs"), "fn b() {}\n").unwrap();
        std::fs::write(dir.join("README.md"), "# hi\n").unwrap();
        std::fs::write(dir.join("target/debug/junk.rs"), "fn junk() {}\n").unwrap(); // skipped

        let profile = profile_repo(&dir);
        // Counts a.rs, b.rs, README.md — but not anything under target/.
        assert_eq!(profile.file_count, 3);
        assert!(profile.total_bytes > 0);
        assert_eq!(profile.primary_language, "rust");

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// A tool that returns a fixed, sizeable string — used to grow history quickly so
    /// compaction triggers deterministically.
    struct BigTool;

    #[async_trait]
    impl Tool for BigTool {
        fn name(&self) -> &str {
            "big"
        }
        fn description(&self) -> &str {
            "returns a large blob"
        }
        fn schema(&self) -> Value {
            json!({ "type": "object", "properties": {} })
        }
        async fn invoke(&self, _args: Value) -> Result<ToolOutput, ToolError> {
            Ok(ToolOutput::ok("lorem ipsum dolor sit amet ".repeat(20)))
        }
    }

    /// Records every request's `(model, has_tools, system)` and routes the reply: a tool-less
    /// request (the compaction summary call) gets a short summary; a tool-bearing request pops
    /// the next scripted main-loop turn.
    struct RecordingProvider {
        seen: Mutex<Vec<(String, bool, String)>>,
        main_turn: AtomicUsize,
        main_scripts: Vec<Vec<Event>>,
    }

    impl RecordingProvider {
        fn new(main_scripts: Vec<Vec<Event>>) -> Arc<Self> {
            Arc::new(Self {
                seen: Mutex::new(Vec::new()),
                main_turn: AtomicUsize::new(0),
                main_scripts,
            })
        }
    }

    #[async_trait]
    impl Provider for RecordingProvider {
        async fn stream(
            &self,
            req: ChatRequest,
        ) -> Result<
            BoxStream<'static, Result<Event, lvz_protocol::ProviderError>>,
            lvz_protocol::ProviderError,
        > {
            let has_tools = !req.tools.is_empty();
            let system = req
                .system
                .as_ref()
                .map(|s| s.text.clone())
                .unwrap_or_default();
            self.seen
                .lock()
                .unwrap()
                .push((req.model.clone(), has_tools, system));

            let events = if has_tools {
                let n = self.main_turn.fetch_add(1, Ordering::SeqCst);
                self.main_scripts.get(n).cloned().unwrap_or_default()
            } else {
                // Compaction summary call.
                vec![
                    Event::TextDelta("- summarised earlier work".into()),
                    Event::Usage(Usage {
                        input_tokens: 30,
                        output_tokens: 8,
                        ..Default::default()
                    }),
                    Event::Done(StopReason::EndTurn),
                ]
            };
            Ok(stream::iter(events.into_iter().map(Ok)).boxed())
        }

        fn capabilities(&self) -> Capabilities {
            Capabilities::default()
        }
    }

    fn big_tool_turn(id: &str) -> Vec<Event> {
        vec![
            Event::ToolUseStart {
                id: id.into(),
                name: "big".into(),
            },
            Event::ToolUseEnd { id: id.into() },
            Event::Usage(Usage {
                input_tokens: 20,
                output_tokens: 5,
                ..Default::default()
            }),
            Event::Done(StopReason::ToolUse),
        ]
    }

    #[tokio::test]
    async fn compacts_history_when_over_budget_and_routes_to_summary_model() {
        // Four big-tool turns grow history past the tiny compact_after, then a final answer.
        let mut main = vec![
            big_tool_turn("a"),
            big_tool_turn("b"),
            big_tool_turn("c"),
            big_tool_turn("d"),
        ];
        main.push(vec![
            Event::TextDelta("all done".into()),
            Event::Usage(Usage {
                input_tokens: 15,
                output_tokens: 4,
                ..Default::default()
            }),
            Event::Done(StopReason::EndTurn),
        ]);
        let provider = RecordingProvider::new(main);

        let mut registry = ToolRegistry::new();
        registry.register(Arc::new(BigTool));

        let knobs = Knobs {
            compact_after: 5, // tiny: any real history exceeds it
            ..Knobs::default()
        };
        let agent = Agent::new(
            provider.clone(),
            registry,
            AgentConfig::default().with_summary_model("haiku-cheap"),
        )
        .with_tuner(Arc::new(FixedTuner(knobs)));

        let events = collect(agent.run("do a multi-step task")).await;

        // Completed normally.
        assert!(events
            .iter()
            .any(|e| matches!(e, Event::Done(StopReason::EndTurn))));

        let seen = provider.seen.lock().unwrap();
        // At least one tool-less request was made (the compaction summary call)...
        let summary_calls: Vec<_> = seen
            .iter()
            .filter(|(_, has_tools, _)| !*has_tools)
            .collect();
        assert!(
            !summary_calls.is_empty(),
            "expected a compaction summary call"
        );
        // ...and it was routed to the cheap summary model with the compaction system prompt.
        let (model, _, system) = summary_calls[0];
        assert_eq!(model, "haiku-cheap");
        assert!(system.contains("compress"), "compaction system prompt used");
    }
}
